import { useMemo, useState } from "react";
import { CheckCircle2, LockKeyhole, ArrowRight, ArrowLeft } from "lucide-react";
import { useGetAssessment, useSubmitAssessmentResponse, getGetAssessmentQueryKey } from "@workspace/api-client-react";
import { Button } from "@workspace/nros-design-system/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/nros-design-system/components/ui/card";
import { Progress } from "@workspace/nros-design-system/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@workspace/nros-design-system/components/ui/radio-group";
import { Label } from "@workspace/nros-design-system/components/ui/label";
import { Skeleton } from "@workspace/nros-design-system/components/ui/skeleton";
import { EmptyState } from "./dashboard";
export function AssessmentPage() {
 const {data,isLoading,isError}=useGetAssessment({ query: { queryKey: getGetAssessmentQueryKey() } }); const submit=useSubmitAssessmentResponse(); const [step,setStep]=useState(0); const [answers,setAnswers]=useState<Record<string,string>>({}); const [done,setDone]=useState(false);
 const question=useMemo(()=>data?.questions?.[step],[data,step]); if(isLoading)return <div className="mx-auto max-w-2xl space-y-5"><Skeleton className="h-10 w-2/3"/><Skeleton className="h-72"/></div>; if(isError||!data)return <EmptyState title="Avaliação indisponível" text="A avaliação ativa ainda não está disponível."/>; if(done)return <div className="mx-auto max-w-lg py-12"><Card><CardContent className="flex flex-col items-center py-14 text-center"><span className="mb-5 flex size-14 items-center justify-center rounded-full bg-secondary text-primary"><CheckCircle2 className="size-7"/></span><h1 className="text-2xl font-semibold">Resposta registrada</h1><p className="mt-3 text-muted-foreground">Obrigado por contribuir. Sua percepção foi recebida de forma anônima.</p></CardContent></Card></div>;
 const total=data.questions.length; const isLast=step===total-1; const choice=answers[String(question?.id)];
 const next=()=>{if(!choice)return;if(isLast){submit.mutate({data:{assessmentId:data.id,answers}},{onSuccess:()=>setDone(true)});}else setStep(s=>s+1)};
 return <div className="mx-auto max-w-2xl space-y-6"><div><p className="text-sm font-medium text-primary">Participação anônima</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{data.title}</h1><p className="mt-2 text-muted-foreground">{data.description}</p></div><Card className="border-primary/20 bg-primary/5"><CardContent className="flex gap-3 p-4"><LockKeyhole className="mt-0.5 size-5 shrink-0 text-primary"/><div><p className="text-sm font-semibold">Sua privacidade está protegida</p><p className="mt-1 text-sm text-muted-foreground">{data.privacyNote}</p></div></CardContent></Card><div className="flex items-center justify-between text-sm"><span className="font-medium">Pergunta {step+1} de {total}</span><span className="text-muted-foreground">{Math.round(((step+1)/total)*100)}%</span></div><Progress value={((step+1)/total)*100}/><Card><CardHeader><CardTitle className="text-xl leading-relaxed">{question?.text}</CardTitle></CardHeader><CardContent><RadioGroup value={choice} onValueChange={v=>setAnswers({...answers,[String(question?.id)]:v})} className="gap-3">{question?.options.map((option,i)=><Label key={option} htmlFor={`option-${i}`} className="flex cursor-pointer items-center gap-3 rounded-lg border bg-card p-4 text-sm transition-colors hover:border-primary has-[[data-state=checked]]:border-primary has-[[data-state=checked]]:bg-primary/5" data-testid={`label-option-${i}`}><RadioGroupItem id={`option-${i}`} value={option} data-testid={`radio-option-${i}`}/>{option}</Label>)}</RadioGroup></CardContent></Card><div className="flex justify-between"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)} data-testid="button-previous"><ArrowLeft/>Anterior</Button><Button disabled={!choice||submit.isPending} onClick={next} data-testid="button-next">{isLast?"Enviar resposta":"Próxima pergunta"}<ArrowRight/></Button></div></div>;
}