import { useState } from "react";
import type { FormEvent } from "react";
import { Plus, CalendarDays } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { useCreateActionPlan, useGetActionPlans, getGetActionPlansQueryKey } from "@workspace/api-client-react";
import { Button } from "@workspace/nros-design-system/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/nros-design-system/components/ui/card";
import { Input } from "@workspace/nros-design-system/components/ui/input";
import { Label } from "@workspace/nros-design-system/components/ui/label";
import { Badge } from "@workspace/nros-design-system/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@workspace/nros-design-system/components/ui/dialog";
import { EmptyState } from "./dashboard";
export function PlansPage() {
 const { data, isLoading, isError } = useGetActionPlans(); const create = useCreateActionPlan(); const qc = useQueryClient(); const [open,setOpen]=useState(false); const [form,setForm]=useState({title:"",owner:"",dueDate:"",priority:"medium" as "low"|"medium"|"high",source:"Ciclo atual"});
 const submit=(e:FormEvent)=>{e.preventDefault();create.mutate({data:form},{onSuccess:()=>{qc.invalidateQueries({queryKey:getGetActionPlansQueryKey()});setOpen(false);setForm({title:"",owner:"",dueDate:"",priority:"medium",source:"Ciclo atual"});}})};
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-primary">Execução responsável</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Plano de ação</h1><p className="mt-2 text-muted-foreground">Transforme sinais em compromissos claros, com dono e prazo.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button data-testid="button-create-plan"><Plus />Nova ação</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nova ação</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="title">Ação</Label><Input id="title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} data-testid="input-plan-title" /></div><div><Label htmlFor="owner">Responsável</Label><Input id="owner" required value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} data-testid="input-plan-owner" /></div><div><Label htmlFor="dueDate">Prazo</Label><Input id="dueDate" type="date" required value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} data-testid="input-plan-date" /></div><Button type="submit" disabled={create.isPending} className="w-full" data-testid="button-submit-plan">{create.isPending?"Salvando…":"Criar plano"}</Button></form></DialogContent></Dialog></div>
 {isLoading?<Card><CardContent className="py-12 text-center text-muted-foreground">Carregando compromissos…</CardContent></Card>:isError?<EmptyState title="Não foi possível carregar o plano" text="Tente novamente em alguns instantes." />:!data?.length?<EmptyState title="Nenhuma ação registrada" text="Crie o primeiro compromisso para começar a acompanhar a resposta." />:<div className="grid gap-4 lg:grid-cols-2">{data.map(a=><Card key={a.id} data-testid={`card-action-${a.id}`}><CardHeader className="pb-3"><div className="flex justify-between gap-3"><CardTitle className="text-base">{a.title}</CardTitle><Badge variant={a.priority==="high"?"destructive":"secondary"}>{a.priority==="high"?"Alta":a.priority==="medium"?"Média":"Baixa"}</Badge></div><p className="text-sm text-muted-foreground">{a.source}</p></CardHeader><CardContent><div className="flex items-center justify-between text-sm"><span>Responsável: <strong>{a.owner}</strong></span><span className="flex items-center gap-1 text-muted-foreground"><CalendarDays className="size-4" />{new Date(a.dueDate).toLocaleDateString("pt-BR")}</span></div><div className="mt-4"><Badge variant="outline">{a.status==="done"?"Concluída":a.status==="in_progress"?"Em andamento":"Planejada"}</Badge></div></CardContent></Card>)}</div>}</div>
}